import comp from "/Users/aimwhy/Desktop/工作文档/zy/vuepress/zy-vuepress/src/.vuepress/.temp/pages/zh/posts/interview/notes.html.vue"
const data = JSON.parse("{\"path\":\"/zh/posts/interview/notes.html\",\"title\":\"面试注意事项\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"面试注意事项\",\"date\":\"2019-05-27T00:00:00.000Z\",\"tags\":[\"面试\"],\"gitInclude\":[],\"description\":\"​ 又是七月面试季节，又一波大学生进入社会，面临着各种面试问题，网上有很多面经，但更多的是在讲面试的经历或者面试被问到的技术相关的。这里我给大家分享一些无关乎技术，但在面试中需要注意的一些事项。 友情提示：去面试的时候，千万别空着手去啊！ 不要误会，不是让你给面试官送礼，毕竟我们都是金光闪闪的程序员，靠技术说话，不吃这一套。 带上个人简历 面试的时候：...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/zy-vuepress/zh/posts/interview/notes.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"面试注意事项\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"​ 又是七月面试季节，又一波大学生进入社会，面临着各种面试问题，网上有很多面经，但更多的是在讲面试的经历或者面试被问到的技术相关的。这里我给大家分享一些无关乎技术，但在面试中需要注意的一些事项。 友情提示：去面试的时候，千万别空着手去啊！ 不要误会，不是让你给面试官送礼，毕竟我们都是金光闪闪的程序员，靠技术说话，不吃这一套。 带上个人简历 面试的时候：...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"面试\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-05-27T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"面试注意事项\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2019-05-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zoe\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"带上个人简历\",\"slug\":\"带上个人简历\",\"link\":\"#带上个人简历\",\"children\":[]},{\"level\":2,\"title\":\"面试官是个怎样的人\",\"slug\":\"面试官是个怎样的人\",\"link\":\"#面试官是个怎样的人\",\"children\":[]},{\"level\":2,\"title\":\"你有什么想问的？\",\"slug\":\"你有什么想问的\",\"link\":\"#你有什么想问的\",\"children\":[]},{\"level\":2,\"title\":\"不要被期权、股权诱惑\",\"slug\":\"不要被期权、股权诱惑\",\"link\":\"#不要被期权、股权诱惑\",\"children\":[]},{\"level\":2,\"title\":\"公积金和社保给怎么交\",\"slug\":\"公积金和社保给怎么交\",\"link\":\"#公积金和社保给怎么交\",\"children\":[]},{\"level\":2,\"title\":\"不尊重你和你的财产的公司\",\"slug\":\"不尊重你和你的财产的公司\",\"link\":\"#不尊重你和你的财产的公司\",\"children\":[]},{\"level\":2,\"title\":\"多了解下公司文化\",\"slug\":\"多了解下公司文化\",\"link\":\"#多了解下公司文化\",\"children\":[]},{\"level\":2,\"title\":\"尽量去大厂，尽量不要去外包公司\",\"slug\":\"尽量去大厂-尽量不要去外包公司\",\"link\":\"#尽量去大厂-尽量不要去外包公司\",\"children\":[]}],\"readingTime\":{\"minutes\":7.12,\"words\":2135},\"filePathRelative\":\"zh/posts/interview/notes.md\",\"localizedDate\":\"2019年5月27日\",\"excerpt\":\"<p>​<br>\\n又是七月面试季节，又一波大学生进入社会，面临着各种面试问题，网上有很多面经，但更多的是在讲面试的经历或者面试被问到的技术相关的。这里我给大家分享一些无关乎技术，但在面试中需要注意的一些事项。</p>\\n<blockquote>\\n<p>友情提示：去面试的时候，千万别空着手去啊！</p>\\n</blockquote>\\n<p>不要误会，不是让你给面试官送礼，毕竟我们都是金光闪闪的程序员，靠技术说话，不吃这一套。</p>\\n<h2>带上个人简历</h2>\\n<p>面试的时候：一定要带简历！带简历！带简历！重要的事情说三遍。我在面试其他人的时候，都会先看对方的简历，然后才开始面试。从你的简历中能够看出非常多的信息，甚至看到你的简历就能初步确定你是不是我们要找的人（因为约面试一般是hr处理的，技术面你时不一定看过你的简历）。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
