import comp from "/Users/aimwhy/Desktop/工作文档/zy/vuepress/zy-vuepress/src/.vuepress/.temp/pages/zh/posts/webframe/javascript/index.html.vue"
const data = JSON.parse("{\"path\":\"/zh/posts/webframe/javascript/\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"gitInclude\":[],\"description\":\"目录 交流群讨论问题整理(整理中) 【编程 】模仿实现new创建对象 【编程】实现一个instanceof 【编程 】如何实现一个call函数？ 【编程 】如何实现一个bind函数？ 【编程】如何实现一个apply函数？ 【QA001 】为什么for 循环的性能远远高于 forEach 的性能 【QA002 】JS浮点运算不准确,如何解决？ 【QA00...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/zy-vuepress/zh/posts/webframe/javascript/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的博客\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"目录 交流群讨论问题整理(整理中) 【编程 】模仿实现new创建对象 【编程】实现一个instanceof 【编程 】如何实现一个call函数？ 【编程 】如何实现一个bind函数？ 【编程】如何实现一个apply函数？ 【QA001 】为什么for 循环的性能远远高于 forEach 的性能 【QA002 】JS浮点运算不准确,如何解决？ 【QA00...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zoe\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"目录\",\"slug\":\"目录\",\"link\":\"#目录\",\"children\":[]},{\"level\":2,\"title\":\"交流群讨论问题整理(整理中)\",\"slug\":\"交流群讨论问题整理-整理中\",\"link\":\"#交流群讨论问题整理-整理中\",\"children\":[]}],\"readingTime\":{\"minutes\":1.1,\"words\":330},\"filePathRelative\":\"zh/posts/webframe/javascript/README.md\",\"excerpt\":\"<h2>目录</h2>\\n<ul>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/datatype.html\\\" target=\\\"_blank\\\"><code>[数据类型]</code> 经常被面试官问道的JavaScript数据类型知识你真的懂吗？</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/scoped.html\\\" target=\\\"_blank\\\"><code>[作用域]</code>深入理解 JavaScript, 从作用域与作用域链开始</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/closure.html\\\" target=\\\"_blank\\\"><code>[闭包]</code>理解javascript中的闭包</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/higherFunc.html\\\" target=\\\"_blank\\\"><code>[高阶函数]</code>高阶函数详解与实战训练</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/copy.html\\\" target=\\\"_blank\\\"><code>[赋值拷贝]</code>js中赋值•浅拷贝•深拷贝</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/prototype.html\\\" target=\\\"_blank\\\"><code>[原型链]</code>原型链这么看好像并不难</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/this.html\\\" target=\\\"_blank\\\"><code>[this]</code>this关键字</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/unique.html\\\" target=\\\"_blank\\\">如何答一道惊艳面试官的数组去重问题？</a></li>\\n<li><a href=\\\"/zy-vuepress/webframe/javascript/exports.html\\\" target=\\\"_blank\\\">exports和module.exports的区别</a></li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
